CREATE TABLE categories (
	idt_category int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nam_category varchar(255) NULL,
	CONSTRAINT categories_pkey PRIMARY KEY (idt_category)
);

CREATE TABLE orders (
	idt_order int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	dat_creation timestamp(6) NULL,
	cod_customer varchar(255) NULL,
	des_status varchar(255) NULL,
	num_price numeric(38, 2) NULL,
	cod_external_payment varchar(255) NULL,
	CONSTRAINT orders_des_status_check CHECK (((des_status)::text = ANY ((ARRAY['RECEIVED'::character varying, 'WAITING_PAYMENT'::character varying, 'PAID'::character varying, 'CANCELED'::character varying, 'IN_PREPARATION'::character varying, 'FINISHED'::character varying])::text[]))),
	CONSTRAINT orders_pkey PRIMARY KEY (idt_order)
);


CREATE TABLE products (
	idt_product int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	des_product varchar(255) NULL,
	flg_active bool NULL,
	nam_product varchar(255) NULL,
	num_price_product numeric(38, 2) NULL,
	idt_category int8 NULL,
	CONSTRAINT products_pkey PRIMARY KEY (idt_product),
	CONSTRAINT fk5j0lmla98i86ghdlalpaqot6b FOREIGN KEY (idt_category) REFERENCES categories(idt_category)
);


CREATE TABLE order_products (
	idt_order_product int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	idt_order int8 NULL,
	idt_product int8 NULL,
	CONSTRAINT order_products_pkey PRIMARY KEY (idt_order_product),
	CONSTRAINT fkmwy3mmfm750cgmhgv7h9eiowi FOREIGN KEY (idt_product) REFERENCES products(idt_product),
	CONSTRAINT fko5uq4bmn58hoh698rxevw22c6 FOREIGN KEY (idt_order) REFERENCES orders(idt_order)
);

INSERT INTO categories(idt_category, nam_category) VALUES
    (1, 'SNACK'),
    (2, 'SIDE-DISH'),
    (3, 'DRINK'),
    (4, 'DESSERT');

INSERT INTO products(des_product, flg_active, nam_product, num_price_product, idt_category) VALUES
    ('180G OF HAMBURGER SNACK WITH NOBLE MEAT', true, 'HAMBURGER SNACK', '30.00', 1),
    ('180G OF CHICKEN BURGER SNACK', true, 'CHICKEN HAMBURGER SNACK', '25.00', 1),
    ('310ML OF COCA-COLA SODA', true, 'COCA-COLA', '5.00', 3),
    ('510ML OF NATURAL WATER', true, 'WATER', '3.00', 3),
    ('180G OF FRENCH FRIES', true, 'FRENCH FRIES', '18.00', 2),
    ('180G OF ONION RINGS', true, 'ONION RINGS', '22.00', 2),
    ('100G OF PUDDING', true, 'PUDDING', '20.00', 4),
    ('100G OF ICE CREAM', true, 'ICE CREAM', '15.00', 4);